# Generated by Django 3.2.20 on 2023-07-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_rename_booking_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='client',
        ),
    ]
